#!/bin/sh
### BEGIN INIT INFO
# Provides:          rf24hub
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Enables /usr/bin/sensorhub
### END INIT INFO

. /lib/lsb/init-functions
SERVICENAME=rf24hub
SENSORHUBPIDFILE=/var/run/rf24hub.pid
if [ -e ${SENSORHUBPIDFILE} ]; then
  SENSORHUBPID=`cat ${SENSORHUBPIDFILE}` > /dev/null 2>1
fi

case "$1" in
  start)
    echo -n "[....] Starting sensorhub "
    if [ ! -e ${SENSORHUBPIDFILE} ]; then 
      /usr/local/bin/rf24hubd -d 
      log_end_msg $?
    else
      echo -n "... already running with PID $SENSORHUBPID"
      log_end_msg 1
    fi
    ;;
  stop)
    echo -n "[....] Stopping sensorhub ..."
    if [ "${SENSORHUBPID}" ]; then 
      kill -15 ${SENSORHUBPID}
      log_end_msg $?
      rm ${SENSORHUBPIDFILE}
    else
      echo -n "not running ..."
      log_end_msg 1
    fi
    ;;
  restart)
	/usr/sbin/service $SERVICENAME stop
	/usr/sbin/service $SERVICENAME start	
	;;
  *)
    echo "Usage: service ${SERVICENAME} {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

