
TARGETDIR=../../wilmsn.github.io/rf24hub
doc:
	markdown README.md > ${TARGETDIR}/index.html
	markdown rf24hub_flow.md > ${TARGETDIR}/rf24hub_flow.html
	markdown quickstartquide.md > ${TARGETDIR}/quickstartquide.html

