
TARGETDIR=../../wilmsn.github.io/rf24hub
doc:
	markdown README.md > ${TARGETDIR}/index.html
	markdown rf24hub_flow.md > ${TARGETDIR}/rf24hub_flow.html
	markdown quickstartquide.md > ${TARGETDIR}/quickstartguide.html
	markdown DB_GUIDE.md > ${TARGETDIR}/dbguide.html
	markdown AVR_GUIDE.md > ${TARGETDIR}/avrguide.html
	markdown ESP_GUIDE.md > ${TARGETDIR}/espguide.html
	markdown README_doc.md > ${TARGETDIR}/doku.html
	cp overview.png ${TARGETDIR}/overview.png
	cp Avr_minimal_Schaltplan.png ${TARGETDIR}/Avr_minimal_Schaltplan.png
	cp Arduino_IDE_settings.png ${TARGETDIR}/Arduino_IDE_settings.png
